version: "2"
services:
    nginx:
        image: nginxproxy/nginx-proxy
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /var/docker/nginx/html:/usr/share/nginx/html
            - /var/docker/nginx/certs:/etc/nginx/certs
            - /var/docker/nginx/vhost:/etc/nginx/vhost.d
            - ./nginx.conf:/etc/nginx/nginx.conf
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    letsencrypt-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: unless-stopped
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/docker/nginx/acme:/etc/acme.sh
        environment:
            DEFAULT_EMAIL: thold88@gmail.com
    
    website:
        image: wordpress
        volumes:
            - ./hometaxi:/var/www/html
        environment:
            WORDPRESS_DB_HOST: xeghep24h_website-db_1:3306
            WORDPRESS_DB_USER: hometaxi
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: hometaxi
            VIRTUAL_HOST: xeghep24h.vn
            LETSENCRYPT_HOST: xeghep24h.vn
        depends_on:
            - website-db
        restart: unless-stopped
        volumes:
            - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini

    website-db:
        image: mariadb:10.8.2
        volumes:
            - ./hometaxi-db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: hometaxi
            MYSQL_USER: hometaxi
            MYSQL_PASSWORD: password
        restart: unless-stopped
